---

- name: using Python 3.6.11
  set_fact:
    PYTHON_VERSION: 3.6.11
    APP_DIR: /var/app/pyconjp/pyconjpbot

- name: install python {{ PYTHON_VERSION }} by pyenv
  command: /root/.pyenv/bin/pyenv install {{ PYTHON_VERSION }} --skip-existing

- name: Clone pyconjpbot from github
  git:
    repo: https://github.com/pyconjp/pyconjpbot.git
    dest: "{{ APP_DIR }}"
    version: master
    depth: 1

- name: pip install to venv
  pip:
    requirements: "{{ APP_DIR }}/requirements.txt"
    virtualenv: "{{ APP_DIR }}/venv"
    virtualenv_command: "/root/.pyenv/shims/python -m venv"
  environment:
    PYENV_VERSION: "{{ PYTHON_VERSION }}"

- name: write slackbot_settings.py from vault credentials file
  copy:
    mode: 0600
    content: |
      # Settings for slackbot

      # API Token for Bot integration
      # https://pyconjp.slack.com/services/B15KRL7CY
      API_TOKEN = "<your-api-token>"

      DEFAULT_REPLY = "コマンドが不明です。ヘルプを参照してください https://github.com/pyconjp/pyconjpbot#commands"

      ERRORS_TO = 'pyconjpbot-test'

      PLUGINS = [
          #'slackbot.plugins',
          'pyconjpbot.plugins',
          'pyconjpbot.google_plugins',
      ]

      ALIASES = '$'

      # Settings for jira plugin
      JIRA_URL = 'https://pyconjp.atlassian.net/'
      JIRA_PROJECTS = ['ISSHA', 'SAR', 'TRI', 'INU']  # JIRA Project Keys
      JIRA_DEFAULT_PROJECT = 'INU'   # JIRA Default Project Key

      # see https://docs.google.com/spreadsheets/d/1YiqErBDdp5QWfTlfDmxc6Vi696b_NGFJKzuyM-v6PDM/edit#gid=0
      # https://id.atlassian.com/manage/api-tokens でトークンを生成
      JIRA_USERNAME = '<JIRA Username>'
      JIRA_USER = '<JIRA Email>'
      JIRA_PASS = '<JIRA API Token>'

      # Settings for translator plugin
      # https://www.microsoft.com/ja-jp/translator/getstarted.aspx
      TRANSLATOR_API_KEY = '<Your Subscription Key>'

      # Settings for github plugin
      GITHUB_TOKEN = '<Your Github Token>'
      GITHUB_ORGANIZATION = '<Your organization>'
    dest: "{{ APP_DIR }}/slackbot_settings.py"
