---

- name: using Python 3.9.13
  set_fact:
    PYTHON_VERSION: 3.9.13
    APP_DIR: /var/app/pyconjp/pyconjpbot

- name: install python {{ PYTHON_VERSION }} by pyenv
  command: /root/.pyenv/bin/pyenv install {{ PYTHON_VERSION }} --skip-existing

- name: Clone pyconjpbot from github
  git:
    repo: https://github.com/pyconjp/pyconjpbot.git
    dest: "{{ APP_DIR }}"
    version: master
    depth: 1

- name: pip install to venv
  pip:
    requirements: "{{ APP_DIR }}/requirements.txt"
    virtualenv: "{{ APP_DIR }}/venv"
    virtualenv_command: "/root/.pyenv/shims/python -m venv"
  environment:
    PYENV_VERSION: "{{ PYTHON_VERSION }}"

- name: write slackbot_settings.py from vault credentials file
  copy:
    mode: 0600
    content: |
      ## Settings for slackbot

      # API Token for Bot integration
      # https://pyconjp.slack.com/services/B15KRL7CY
      API_TOKEN = "{{ API_TOKEN }}"

      DEFAULT_REPLY = "コマンドが不明です。ヘルプを参照してください https://github.com/pyconjp/pyconjpbot#commands"

      ERRORS_TO = 'pyconjpbot-error'

      PLUGINS = [
        'pyconjpbot.plugins',
        'pyconjpbot.google_plugins',
      ]

      ALIASES = '$'

      import logging
      fmt = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      logging.basicConfig(format=fmt, filename='pyconjpbot.log', level=logging.DEBUG)

      # Settings for jira plugin
      JIRA_URL = 'https://pyconjp.atlassian.net/'
      JIRA_PROJECTS = ['ISSHA', 'WYI', 'NEZ']  # JIRA Project Keys
      JIRA_DEFAULT_PROJECT = 'ISSHA'  # JIRA Default Project Key

      # see https://docs.google.com/spreadsheets/d/1YiqErBDdp5QWfTlfDmxc6Vi696b_NGFJKzuyM-v6PDM/edit#gid=0
      # https://id.atlassian.com/manage/api-tokens でトークンを生成
      JIRA_USERNAME = 'jirabot'
      JIRA_USER = 'contact+jirabot@pycon.jp'
      JIRA_PASS = '{{ JIRA_PASS }}'

      ## Settings for translator plugin
      # https://www.microsoft.com/en-us/translator/getstarted.aspx
      TRANSLATOR_API_KEY = '{{ TRANSLATOR_API_KEY }}'

      ## Settings for github plugin
      GITHUB_TOKEN = '{{ GITHUB_TOKEN }}'
      GITHUB_ORGANIZATION = 'pyconjp'
    dest: "{{ APP_DIR }}/slackbot_settings.py"

- name: write token.json from vault token file
  copy:
    mode: 0600
    content: |
      {{ GOOGLE_TOKEN }}
    dest: "{{ APP_DIR }}/pyconjpbot/google_plugins/token.json"

- name: Copy systemd files
  copy: src=etc/systemd/system/pyconjpbot.service dest=/etc/systemd/system/pyconjpbot.service owner=root group=root mode=0644

- name: enabled systemd
  systemd: name=pyconjpbot.service state=started enabled=yes daemon_reload=yes

- name: restart systemd
  systemd: name=pyconjpbot.service state=restarted
