---
- hosts: pyconjp
  roles:
    - base
    - { tags: u, role: users }
    - { tags: w2021, role: web-2021 }
    - { tags: w2020, role: web-2020 }
    - { tags: w2019, role: web-2019 }
    - { tags: w2018, role: web-2018 }
    - { tags: w2017, role: web-2017 }
    - { tags: w2016, role: web-2016 }
    - { tags: w2015, role: web-2015 }
    - { tags: w2014, role: web-2014 }
    - { tags: w2013, role: web-2013 }
    - { tags: w2012, role: web-2012 }
    - { tags: w2011, role: web-2011 }
    - { tags: p, role: pyenv }
    - { tags: cron, role: pyconjp-cron }
    - { tags: jira-issue-report, role: jira-issue-report }
    - { tags: bot, role: pyconjpbot }
    - { tags: n, role: nginx }
    - { tags: infra, role: infra }
