---
- set_fact:
    repository: pyconjp/2011.pycon.jp.static
    year: 2011

- git:
    repo: "https://github.com/{{ repository }}.git"
    dest: "/var/app/{{ repository }}"
    version: master
    depth: 1

- file:
    state: link
    src: "/var/app/{{ repository }}"
    dest: "/var/www/2011.pycon.jp"
