---
- set_fact:
    repository: pyconjp/apac-2013.pycon.jp.static
    year: 2013

- git:
    repo: "https://github.com/{{ repository }}.git"
    dest: "/var/app/{{ repository }}"
    version: master
    depth: 1

- file:
    state: link
    src: "/var/app/{{ repository }}"
    dest: "/var/www/apac-2013.pycon.jp"
