---

- name: using Python 3.6.11
  set_fact:
    PYTHON_VERSION: 3.6.11
    APP_DIR: /var/app/pyconjp/pyconjp-cron

- name: install python {{ PYTHON_VERSION }} by pyenv
  command: /root/.pyenv/bin/pyenv install {{ PYTHON_VERSION }} --skip-existing

- name: Clone pyconjp-cron from github
  git:
    repo: https://github.com/pyconjp/pyconjp-cron.git
    dest: "{{ APP_DIR }}"
    version: master
    depth: 1

- name: pip install to venv
  pip:
    requirements: "{{ APP_DIR }}/requirements.txt"
    virtualenv: "{{ APP_DIR }}/venv"
    virtualenv_command: "/root/.pyenv/shims/python -m venv"
  environment:
    PYENV_VERSION: "{{ PYTHON_VERSION }}"

- name: write settings.py from vault credentials file
  copy:
    mode: 0600
    content: |
      # Twitter
      CONSUMER_KEY = '{{ CONSUMER_KEY }}'
      CONSUMER_SECRET = '{{ CONSUMER_SECRET }}'
      ACCESS_TOKEN = '{{ ACCESS_TOKEN }}'
      ACCESS_TOKEN_SECRET = '{{ ACCESS_TOKEN_SECRET }}'

      # Facebook
      APP_ID = '{{ APP_ID }}'
      APP_SECRET = '{{ APP_SECRET }}'
      PAGE_ID = '{{ PAGE_ID }}'
      FB_ACCESS_TOKEN = '{{ FB_ACCESS_TOKEN }}'
      FB_PAGE_ACCESS_TOKEN = '{{ FB_PAGE_ACCESS_TOKEN }}'

      # Slack API token
      # https://api.slack.com/custom-integrations/legacy-tokens
      SLACK_TOKEN = '{{ SLACK_TOKEN }}'
    dest: "{{ APP_DIR }}/settings.py"

# root crontab -l (/var/spool/cron/crontabs/root)
# for test cron module
- name: version
  cron:
    name: pyconjp-cron/version
    state: present
    disabled: no
    job: cd {{ APP_DIR }} && venv/bin/python --version >> /tmp/cron.log

- name: sns_notify.py
  cron:
    name: pyconjp-cron/sns_notify.py
    state: present
    disabled: yes
    job: cd {{ APP_DIR }} && venv/bin/python sns_notify.py
    minute: "*/5"

- name: update_calendar.py
  cron:
    name: pyconjp-cron/update_calendar.py
    state: present
    disabled: yes
    job: export LANG=en_US.utf8; cd {{ APP_DIR }} && venv/bin/python update_calendar.py
    minute: "0"
    hour: "9"

- name: slack_channels_list.py
  cron:
    name: pyconjp-cron/slack_channels_list.py
    state: present
    disabled: yes
    job: cd {{ APP_DIR }} && venv/bin/python slack_channels_list.py
    minute: "30"
    hour: "9"
